VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "Task"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False

Public TaskNo As String
Public TaskName As String
Public Period As Long
Public Priority As Long
Public PrevTasks As String
Public StartDate As Date
Public Progress As Double
Public ScheduledStartDate As Date

